openapi: 3.0.0
info:
  title: dwAPI
  version: '3.0'
servers:
  - url: 'http://localhost/v3'
    description: v3
paths:
  /user/login:
    parameters: []
    get:
      summary: User login
      tags: []
      responses:
        '200':
          description: OK
          headers: {}
      operationId: user-login
      parameters:
        - schema:
            type: string
          in: query
          name: project
          description: test
        - schema:
            type: string
          in: query
          name: entity
        - schema:
            type: string
            example: Basic xxx
          in: header
          name: Authorization
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      security:
        - basicAuth: []
      response:
        '401':
           $ref: '#/components/responses/UnauthorizedError'
components:
  schemas: {}
  securitySchemes:
    basicAuth:
      description: 'Basic HTTP authentication. Allowed headers-- Authorization: Basic <api_key> | Authorization: Basic <base64 hash of `api_key:`>'
      scheme: basic
      type: http
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      headers:
        WWW_Authenticate:
          schema:
            type: string      
